import os
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import Optional, Dict, Any
from app.services.github_uploader import upload_jmx_to_github, get_repo_owner

router = APIRouter()


class GitHubUploadRequest(BaseModel):
    repo_name: str
    branch: str = "main"
    jmx_content: str
    jmx_filename: str = "generated_test_plan.jmx"
    csv_files: Optional[dict] = None
    commit_message: Optional[str] = None
    subfolder: str = ""
    owner_override: Optional[str] = None
    execution_profile: Optional[Dict[str, Any]] = None
    advanced_options: Optional[Dict[str, Any]] = None


def build_config_yml(use_case_name: str, execution_profile: Optional[dict], advanced_options: Optional[dict]) -> str:
    """Build a config.yml string from the provided parameters."""
    lines = ["# Auto-generated by AI Performance Script Generator"]
    lines.append(f"use_case: {use_case_name}")
    lines.append("")

    if execution_profile:
        lines.append("execution_profile:")
        lines.append(f"  virtual_users: {execution_profile.get('users', 50)}")
        lines.append(f"  ramp_up_seconds: {execution_profile.get('ramp_up', 60)}")
        lines.append(f"  duration_seconds: {execution_profile.get('duration', 300)}")
        lines.append(f"  think_time_ms: {execution_profile.get('think_time', 1500)}")
        lines.append(f"  pacing_ms: {execution_profile.get('pacing', 0)}")
        lines.append("")

    if advanced_options:
        lines.append("deployment:")
        lines.append(f"  number_of_slaves: {advanced_options.get('num_slaves', 1)}")
        lines.append(f"  write_to_database: {'true' if advanced_options.get('write_to_db', False) else 'false'}")
        lines.append(f"  start_immediately: {'true' if advanced_options.get('start_immediately', True) else 'false'}")

    return "\n".join(lines)


@router.post("/github/upload")
def upload_to_github(request: GitHubUploadRequest):
    """Upload generated JMX and data files to a GitHub repository."""
    from dotenv import load_dotenv
    backend_dir = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    load_dotenv(os.path.join(backend_dir, ".env"), override=True)

    token = os.getenv("REPO_UPLOAD_TOKEN", "") or os.getenv("GITHUB_UPLOAD_TOKEN", "")
    if not token:
        raise HTTPException(
            status_code=400,
            detail={
                "code": "GITHUB_TOKEN_NOT_CONFIGURED",
                "message": "GitHub upload token is not configured. Add REPO_UPLOAD_TOKEN or GITHUB_UPLOAD_TOKEN to backend/.env",
            },
        )

    # Use owner/subfolder from env if not explicitly provided in request
    owner = request.owner_override or os.getenv("GITHUB_UPLOAD_OWNER", "") or None
    base_path = os.getenv("GITHUB_UPLOAD_PATH", "automated-usecases")
    subfolder = f"{base_path}/{request.subfolder.strip('/')}" if request.subfolder else base_path

    try:
        # Build config.yml if execution_profile or advanced_options provided
        extra_files = None
        if request.execution_profile or request.advanced_options:
            config_content = build_config_yml(request.subfolder, request.execution_profile, request.advanced_options)
            extra_files = {"config.yml": config_content}

        single_commit = os.getenv("GITHUB_UPLOAD_SINGLE_COMMIT", "false").lower() == "true"

        result = upload_jmx_to_github(
            repo_name=request.repo_name,
            jmx_content=request.jmx_content,
            jmx_filename=request.jmx_filename,
            csv_files=request.csv_files,
            branch=request.branch,
            commit_message=request.commit_message,
            token=token,
            subfolder=subfolder,
            owner_override=owner,
            single_commit=single_commit,
            extra_files=extra_files,
        )

        if extra_files:
            result["config_uploaded"] = "config.yml" in [u["file"] for u in result.get("uploaded", [])]
            result["config_path"] = f"{subfolder}/config.yml"

        return result
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/github/repos")
def list_repos():
    """List accessible repositories for the authenticated user."""
    from dotenv import load_dotenv
    backend_dir = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    load_dotenv(os.path.join(backend_dir, ".env"), override=True)

    token = os.getenv("REPO_UPLOAD_TOKEN", "") or os.getenv("GITHUB_UPLOAD_TOKEN", "")
    if not token:
        raise HTTPException(
            status_code=400,
            detail="GitHub upload token not configured. Add REPO_UPLOAD_TOKEN or GITHUB_UPLOAD_TOKEN to backend/.env",
        )

    try:
        owner = get_repo_owner(token)
        import requests as req
        resp = req.get(
            f"https://api.github.com/user/repos",
            headers={"Authorization": f"token {token}", "Accept": "application/vnd.github.v3+json"},
            params={"per_page": 100, "sort": "updated"},
            timeout=10,
        )
        resp.raise_for_status()
        repos = [{"name": r["name"], "full_name": r["full_name"], "private": r["private"]} for r in resp.json()]
        return {"owner": owner, "repos": repos}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
